### ISSUE TITLE
External display fix

### ISSUE THREAD

**Issue by hqnicolas** [Xiaoheixu/Thinkpad-T430-s-OpenCorteBootloader#3]
i will fork this OpenCore and add some fixes
- Open Core Patcher Version Update
- Open Core Auxiliary Tools Update
- External Display FIX for Docking Station
- Dual Boot ACPI fix for Windows Sistems
- Original Intel Wifi Card 
- All Tested On Ventura 13.5

https://github.com/hqnicolas/Thinkpad-T430-s-OpenCorteBootloader/releases/tag/T430-Opencore

**Comment by Xiaoheixu** [comment]
I'm very very grateful.

**Comment by Xiaoheixu** [comment]
I'm very  grateful
