### ISSUE TITLE
Intel Core I7-3632qm CPU Freq staying at base clock

### ISSUE THREAD

**Issue by NSlas** [Xiaoheixu/Thinkpad-T430-s-OpenCorteBootloader#4]
I've successfuly upgraded my T430 to mac os ventura from mac os monterey with your EFI (with a little changes tho). But i noticed that the cpu is keep staying at base clock speed. Temperature is fine actully, its currently running on 2.2Mhz and around 60-68 degrees celcius. Is it supposed to run like that or i've missed something important?

![Screenshot 2024-02-13 at 14 12 27](https://github.com/Xiaoheixu/Thinkpad-T430-s-OpenCorteBootloader/assets/94791623/4d755853-00aa-4457-9222-d6ae05a898c7)

**Comment by Xiaoheixu** [comment]
> I've successfuly upgraded my T430 to mac os ventura from mac os monterey with your EFI (with a little changes tho). But i noticed that the cpu is keep staying at base clock speed. Temperature is fine actully, its currently running on 2.2Mhz and around 60-68 degrees celcius. Is it supposed to run like that or i've missed something important?
> 
> 
> 
> ![Screenshot 2024-02-13 at 14 12 27](https://github.com/Xiaoheixu/Thinkpad-T430-s-OpenCorteBootloader/assets/94791623/4d755853-00aa-4457-9222-d6ae05a898c7)
> 
> 

You can try to regenerate a CPUFriend.kext. Maybe my CPUFriend.kext is not working.
